"""User-visible ReAct planning copy generated by the LLM.

The text produced here is not hidden chain-of-thought. It is a concise,
user-facing assessment of the current state and the next action plan.
"""

from __future__ import annotations

import asyncio
import time
from collections.abc import Sequence
from typing import Any

from app.llm.client import ModelTier, complete

_PLANNER_TIMEOUT_SECONDS = 4.0
_PLANNER_RETRY_COOLDOWN_SECONDS = 60.0
_planner_disabled_until = 0.0


AGENT_LABELS: dict[str, str] = {
    "thesis_scout": "赛道前瞻 Agent",
    "deal_sourcing": "项目挖掘 Agent",
    "deal_intake": "项目 Intake Agent",
    "preference_advice": "投资偏好 Agent",
    "file_generation": "文件生成流程",
}

INTENT_LABELS: dict[str, str] = {
    "chat": "通用问答",
    "thesis_scout": "赛道研究",
    "deal_sourcing": "项目推荐/项目挖掘",
    "deal_intake": "项目录入与分析",
    "preference_advice": "投资偏好优化",
    "file_generation": "文件生成",
}

VISIBLE_REACT_PLANNER_SYSTEM = """你是 AtomCAP 的可见工作过程撰写器。
你要写给用户看的“当前状态评估 + 下一步工作规划”，而不是隐藏思维链。
要求：
- 只输出 1 段中文，1-2 句，80-180 字。
- 必须基于用户请求、当前流程、当前进度和观察结果，不能只复述进度短语。
- 可以使用第一人称，例如“我需要……我会……”。语气自然、具体。
- Agent 是一套预设上下文和处理流程，不要把 Agent 说成工具，不要写“调用项目挖掘 Agent 这个工具”。
- 只有搜索、读取材料、工商核验、生成文件、执行命令这类外部动作才称为工具。
- 不要出现“第X轮 ReAct”“下一步工作计划”这类标签。
- 不要承诺尚未完成的结果，不要编造候选公司、数据来源或结论。
"""


def agent_label(agent: str | None) -> str:
    if not agent:
        return ""
    return AGENT_LABELS.get(agent, agent)


def _compact(value: Any, *, limit: int = 900) -> str:
    text = str(value or "").strip()
    text = " ".join(text.split())
    return text if len(text) <= limit else f"{text[:limit]}..."


def _clean_plan(text: str) -> str:
    cleaned = text.strip().strip("\"'“”")
    prefixes = (
        "下一步工作计划：",
        "下一步工作计划:",
        "当前状态评估：",
        "当前状态评估:",
        "计划：",
        "计划:",
    )
    for prefix in prefixes:
        if cleaned.startswith(prefix):
            cleaned = cleaned[len(prefix):].strip()
    return _compact(cleaned, limit=220)


def fallback_visible_react_plan(
    *,
    user_request: str,
    agent: str | None = None,
    intent: str | None = None,
    progress: str | None = None,
    observations: Sequence[str] | None = None,
) -> str:
    """Deterministic fallback used when the planner model is unavailable."""
    flow = agent_label(agent)
    intent_label = INTENT_LABELS.get(str(intent or ""), str(intent or "当前任务"))
    observation_items = [item for item in observations or [] if item]
    first_observation = next(iter(observation_items), "")

    if agent == "deal_sourcing":
        progress_text = str(progress or "")
        observation_text = "；".join(observation_items[:3])
        if "搜索策略" in progress_text:
            return (
                "我已经把用户的项目推荐诉求转成可执行的搜索方向，接下来需要用这些方向去找近期融资、产品发布、专利和工商线索。"
                f"如果首轮信号不足，我会继续扩展关键词，而不是直接给出空项目池。{observation_text}"
            ).strip()
        if "公开数据" in progress_text or "市场信号" in progress_text:
            if "暂无" in observation_text or "0" in observation_text:
                return (
                    "首轮公开信号不足，当前结果还不能支撑一个让用户满意的项目池。"
                    "我会扩大搜索词到细分环节、融资事件和公司官网线索，继续寻找可核验的候选项目。"
                )
            return (
                "我已经拿到一批公开信号，需要判断这些材料是否真的指向可跟进的公司，而不是只停留在行业新闻。"
                "下一步会把信号反推成候选项目，并保留可追溯的证据来源。"
            )
        if "候选项目" in progress_text:
            return (
                "当前已经进入候选项目生成阶段，我需要把收集到的信号或扩展搜索策略转成具体公司名单。"
                "如果缺少直接证据，候选会先标记为待核验，后续再通过工商和相关资料补强。"
            )
        if "实体识别" in progress_text or "去重" in progress_text:
            return (
                "候选名单可能存在品牌名、工商主体名和别名混用的问题。"
                "我会先做实体识别和去重，避免同一项目重复出现在最终项目池里。"
            )
        if "工商核验" in progress_text:
            return (
                "现在需要用工商信息验证候选项目是否有可追踪主体，并补充统一社会信用代码、登记状态等基础事实。"
                "核验结果会影响后续评分和推荐理由的可信度。"
            )
        if "匹配度" in progress_text or "排序" in progress_text:
            return (
                "候选项目已经形成，我需要结合机构偏好、赛道匹配、阶段和风险边界进行评分排序。"
                "下一步会把强推荐、可关注和待观察项目分层，避免把低质量候选混进前排。"
            )
        if "相关资料" in progress_text:
            return (
                "项目池候选已经初步筛出，但还需要补齐每个项目近期的重要资料。"
                "我会围绕公司名和别名继续查官网、融资新闻、专利、工商等来源，让用户能直接打开资料核验。"
            )
        if "项目池已生成" in progress_text:
            return (
                "我已经完成候选项目筛选和资料补充，现在需要把结果整理成项目池交付物。"
                "如果候选数量或资料质量仍不足，系统会在过程里标明信息缺口，而不是把缺证据说成确定结论。"
            )
        return (
            "我需要结合用户的项目推荐诉求、机构偏好和可用市场线索，筛出更可能符合投资目标的候选项目。"
            f"根据当前阶段，我会沿着{flow}继续推进，并根据上一轮结果决定是扩展搜索、核验主体还是整理交付。"
        )
    if agent == "thesis_scout":
        return (
            "我需要先把用户的问题转化为可研究的赛道假设，并结合市场信号、产业链位置和机构偏好判断机会质量。"
            f"根据当前状态，我会进入{flow}的处理流程，先明确研究对象，再继续收集和筛选证据。"
        )
    if agent == "deal_intake":
        return (
            "我需要把用户提供的项目材料转成结构化项目画像，并补充外部信息来判断它是否适合进入初筛。"
            f"根据当前状态，我会进入{flow}的处理流程，先识别公司和业务要点，再进行实体对齐与初步研判。"
        )
    if intent == "file_generation" or agent == "file_generation":
        return (
            "我需要把用户的文件生成请求转成可下载的交付文件，并结合当前会话、工作台和机构偏好整理内容。"
            "下一步会调用文件生成工具生成 Word、Excel 或 PPT，并把文件引用保存到当前会话中。"
        )

    context = f"当前识别为{intent_label}"
    if progress:
        context += f"，进度是“{progress}”"
    if first_observation:
        context += f"，已有观察包括：{first_observation}"
    return (
        f"我需要先基于用户的请求“{_compact(user_request, limit=40)}”判断任务边界和可用上下文。"
        f"{context}，接下来我会选择合适的处理流程，并把结果组织成用户可以直接查看和追溯的输出。"
    )


async def generate_visible_react_plan(
    *,
    user_request: str,
    agent: str | None = None,
    intent: str | None = None,
    progress: str | None = None,
    observations: Sequence[str] | None = None,
    state_snapshot: str | None = None,
    allow_overseas: bool = False,
) -> str:
    """Generate a concise visible ReAct planning message with best-effort LLM."""
    global _planner_disabled_until

    fallback = fallback_visible_react_plan(
        user_request=user_request,
        agent=agent,
        intent=intent,
        progress=progress,
        observations=observations,
    )
    if time.monotonic() < _planner_disabled_until:
        return fallback

    prompt = "\n".join(
        part
        for part in (
            f"用户请求：{_compact(user_request, limit=300)}",
            f"识别意图：{INTENT_LABELS.get(str(intent or ''), intent or '未确定')}",
            f"当前 Agent 流程：{agent_label(agent) or '未进入专用 Agent'}",
            f"当前进度：{progress or '正在进行状态评估'}",
            "观察结果：\n" + "\n".join(f"- {_compact(item, limit=160)}" for item in observations or []),
            f"状态快照：{_compact(state_snapshot, limit=700)}" if state_snapshot else "",
        )
        if part.strip()
    )
    try:
        text = await asyncio.wait_for(
            complete(
                ModelTier.FAST,
                [
                    {"role": "system", "content": VISIBLE_REACT_PLANNER_SYSTEM},
                    {"role": "user", "content": prompt},
                ],
                allow_overseas=allow_overseas,
                temperature=0.4,
            ),
            timeout=_PLANNER_TIMEOUT_SECONDS,
        )
        plan = _clean_plan(text)
        if plan:
            return plan
    except Exception:  # noqa: BLE001
        _planner_disabled_until = time.monotonic() + _PLANNER_RETRY_COOLDOWN_SECONDS
    return fallback
